management:
  endpoints:
    prometheus: {}
virtualClusters:
  - name: demo
    targetCluster:
      bootstrapServers: localhost:9092
    gateways:
    - name: mygateway
      portIdentifiesNode:
        bootstrapAddress: localhost:9192
    logNetwork: false
    logFrames: false
filterDefinitions:
  - name: jq-produce
    type: JqProduceRequestFilterFactory
    config:
      jqFilter: .
  - name: jq-fetch
    type: JqFetchResponseFilterFactory
    config:
      jqFilter: '.realnames as $names | .posts[] | {title, author: $names[.author]}'
defaultFilters:
  - jq-produce
  - jq-fetch
